### ISSUE TITLE
Mac platform not supported?

### ISSUE THREAD

**Issue by abngal** [EnvCLI/EnvCLI#15]
Error as executable on OSX Mojave. 
Will mac os be supported in the future?

I am getting the errors on both shells I tried (when I tried the installation step for linux).

```
[1] bash: /usr/local/bin/envcli: cannot execute binary file
[2] zsh: exec format error: envcli
```

_On Mac OSX Mojave 10.14.3
Darwin 18.2.0 Darwin Kernel Version 18.2.0: root:xnu-4903.241.1~1/RELEASE_X86_64 x86_64_

Installation steps done:
> curl -L -o /usr/local/bin/envcli https://dl.bintray.com/envcli/golang/envcli/v0.5.1/envcli_linux_amd64
> chmod +x /usr/local/bin/envcli 

>  ls -al /usr/local/bin/envcli
`-rwxr-xr-x  1 a  admin  12031186 Apr 28 02:59 /usr/local/bin/envcli`

Tried the x86 install, getting the same error.

**Comment by PhilippHeuer** [comment]
Try `https://dl.bintray.com/envcli/golang/envcli/v0.5.1/envcli_darwin_amd64`. There is binary build for mac, but i didn't add it to the readme as i can't test it without a mac.

**Comment by abngal** [comment]
Thanks, it worked.
I can now invoke `envcli -v` successfully from the terminal.
