### ISSUE TITLE
ERRO[0000] no configuration for command npm found

### ISSUE THREAD

**Issue by abngal** [EnvCLI/EnvCLI#16]
Used sample `.envcli.yml` from readme

When running `envcli run npm init`, error is:
>ERRO[0000] no configuration for command npm found

Error is both on mac & ubuntu server 18.04.

**Comment by abngal** [comment]
It worked when I used the sample from `/docs/` folder as the content of `.envcli.yml` file.
https://github.com/EnvCLI/EnvCLI/blob/894398d189df49837edde9ff102a278a92abe3d4/docs/examples/node.md

**Comment by PhilippHeuer** [comment]
Yeah, you need to define each command you want to use in the `.envcli.yml` config. If you have any futher questions feel free to join the discord and ask there.
